#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l walltime=6:00:00
#PBS -l pmem=20gb

module load anaconda3
module load plink

cd $PBS_O_WORKDIR

chmod 755 CombineChenchereren2Chimp.sh #PUT FILENAME HERE	

sh CombineChenchereren2Chimp.sh

chmod 755 Chenchereren2aDNAMapfile.R #PUT FILENAME HERE	

R --file=/storage/home/ama6560/scratch/Malagasy/Chenchereren2/Treemix/Chenchereren2aDNAMapfile.R

chmod 755 TreemixChenchereren2.sh #PUT FILENAME HERE	

sh TreemixChenchereren2.sh

exit;