#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l walltime=6:00:00
#PBS -l pmem=20gb

module load anaconda3
module load plink

cd $PBS_O_WORKDIR

chmod 755 CombineKenyaChimp.sh #PUT FILENAME HERE	

sh CombineKenyaChimp.sh

chmod 755 KenyaaDNAMapfile.R #PUT FILENAME HERE	

R --file=/storage/home/ama6560/scratch/Malagasy/Kenya/Treemix/KenyaaDNAMapfile.R

chmod 755 TreemixKenya.sh #PUT FILENAME HERE	

sh TreemixKenya.sh

exit;