#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l walltime=6:00:00
#PBS -l pmem=20gb

module load anaconda3
module load plink

cd $PBS_O_WORKDIR

chmod 755 CombineHoraHolocenen2Chimp.sh #PUT FILENAME HERE	

sh CombineHoraHolocenen2Chimp.sh

chmod 755 HoraHolocenen2aDNAMapfile.R #PUT FILENAME HERE	

R --file=/storage/home/ama6560/scratch/Malagasy/HoraHolocenen2/Treemix/HoraHolocenen2aDNAMapfile.R

chmod 755 TreemixHoraHolocenen2.sh #PUT FILENAME HERE	

sh TreemixHoraHolocenen2.sh

exit;