#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l walltime=6:00:00
#PBS -l pmem=20gb

module load anaconda3
module load plink

cd $PBS_O_WORKDIR

chmod 755 CombineEthiopiaChimp.sh #PUT FILENAME HERE	

sh CombineEthiopiaChimp.sh

chmod 755 EthiopiaaDNAMapfile.R #PUT FILENAME HERE	

R --file=/storage/home/ama6560/scratch/Malagasy/Ethiopia/Treemix/EthiopiaaDNAMapfile.R

chmod 755 TreemixEthiopia.sh #PUT FILENAME HERE	

sh TreemixEthiopia.sh

exit;