#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l walltime=6:00:00
#PBS -l pmem=20gb

module load anaconda3
module load plink

cd $PBS_O_WORKDIR

chmod 755 CombineFingira6000n1Chimp.sh #PUT FILENAME HERE	

sh CombineFingira6000n1Chimp.sh

chmod 755 Fingira6000n1aDNAMapfile.R #PUT FILENAME HERE	

R --file=/storage/home/ama6560/scratch/Malagasy/Fingira6000n1/Treemix/Fingira6000n1aDNAMapfile.R

chmod 755 TreemixFingira6000n1.sh #PUT FILENAME HERE	

sh TreemixFingira6000n1.sh

exit;