#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l walltime=6:00:00
#PBS -l pmem=20gb

module load anaconda3
module load plink

cd $PBS_O_WORKDIR

chmod 755 CombinePemba700Chimp.sh #PUT FILENAME HERE	

sh CombinePemba700Chimp.sh

chmod 755 Pemba700aDNAMapfile.R #PUT FILENAME HERE	

R --file=/storage/home/ama6560/scratch/Malagasy/Pemba700/Treemix/Pemba700aDNAMapfile.R

chmod 755 TreemixPemba700.sh #PUT FILENAME HERE	

sh TreemixPemba700.sh

exit;