#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l walltime=6:00:00
#PBS -l pmem=20gb

module load anaconda3
module load plink

cd $PBS_O_WORKDIR

chmod 755 CombineHoraHolocenen1Chimp.sh #PUT FILENAME HERE	

sh CombineHoraHolocenen1Chimp.sh

chmod 755 HoraHolocenen1aDNAMapfile.R #PUT FILENAME HERE	

R --file=/storage/home/ama6560/scratch/Malagasy/HoraHolocenen1/Treemix/HoraHolocenen1aDNAMapfile.R

chmod 755 TreemixHoraHolocenen1.sh #PUT FILENAME HERE	

sh TreemixHoraHolocenen1.sh

exit;